services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: production
    command: pnpm run start
    ports:
      - '8080:8080'
    networks:
      - app-network
      - rabbitmq-server_rabbitmq-network
    env_file:
      - .env

networks:
  app-network:
  rabbitmq-server_rabbitmq-network:
    external: true
